import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
const cache = new Map();
function moduleURL(file) {
    file = path.resolve(file);
    if (cache.has(file)) return cache.get(file);
    const source = fs.readFileSync(file, 'utf8').replace(/from (['"])(\.\/[^'"]+)\1/g,
        (_, quote, dependency) => `from ${JSON.stringify(moduleURL(path.resolve(path.dirname(file), dependency)))}`);
    const result = 'data:text/javascript;base64,' + Buffer.from(source).toString('base64');
    cache.set(file, result);
    return result;
}
const {default: Inventory} = await import(moduleURL('inventory.js'));
const {default: StackInteraction, minerStore} = await import(moduleURL('stackInteraction.js'));
const {default: Miner} = await import(moduleURL('miner.js'));
const {workerTiers, minerUpgrades} = await import(moduleURL('gameData.js'));
const inventory = new Inventory();
const interaction = new StackInteraction(inventory);
const miner = new Miner(workerTiers[0]);
const store = minerStore(miner);
miner.storage.Stone = 200;
interaction.click(store, 'Stone', true);
assert.deepEqual(interaction.held, {type:'Stone',count:1});
assert.equal(miner.storage.Stone,199);
interaction.click(interaction.playerStore, 0);
assert.equal(interaction.held,null);
assert.equal(inventory.slots[0].count,1);
interaction.click(store,'Stone');
assert.equal(interaction.held.count,64);
interaction.click(interaction.playerStore,0);
assert.equal(inventory.slots[0].count,64);
assert.equal(interaction.held.count,1);
interaction.click(interaction.playerStore,1,true);
assert.equal(inventory.slots[1].count,1);
assert.equal(interaction.held,null);
interaction.quickTransfer(store,'Stone');
assert.equal(miner.storage.Stone,0);
assert.equal(inventory.slots.filter(Boolean).reduce((n,s)=>n+s.count,0),200);
interaction.quickTransfer(interaction.playerStore,0,store);
assert.equal(miner.storage.Stone,64);
assert.equal(inventory.slots[0],null);
// Swap while holding, then cancel: restore the complete unfinished transaction.
inventory.slots[0]={type:'Gold',count:12};
const before=JSON.stringify(inventory.slots);
interaction.click(store,'Stone');
interaction.click(interaction.playerStore,0);
assert.equal(interaction.held.type,'Gold');
interaction.cancel();
assert.equal(JSON.stringify(inventory.slots),before);
assert.equal(miner.storage.Stone,64);
// Only available capacity moves; overflow remains in miner storage.
inventory.slots=Array.from({length:20},()=>({type:'Stone',count:64}));
inventory.slots[0].count=60;
miner.storage.Stone=100;
interaction.quickTransfer(store,'Stone');
assert.equal(miner.storage.Stone,96);
assert.equal(inventory.slots[0].count,64);
interaction.quickTransfer(store,'Stone');
assert.equal(miner.storage.Stone,96);
// Right-click placement moves one; full stacks cannot swallow cursor contents.
interaction.click(store,'Stone');
interaction.click(interaction.playerStore,0,true);
assert.equal(interaction.held.count,64);
interaction.cancel();assert.equal(miner.storage.Stone,96);
const wallet={balance:0};
assert.equal(miner.buyUpgrade('cycle',wallet),false);
assert.equal(miner.cycleLevel,1);
wallet.balance=10000;
const cost=miner.upgradeCost('cycle');
assert.equal(miner.buyUpgrade('cycle',wallet),true);
assert.equal(wallet.balance,10000-cost);
assert.equal(miner.cycleLevel,2);
miner.resourceLevel=minerUpgrades.maxLevel;
assert.equal(miner.upgradeCost('resources'),null);
const balance=wallet.balance;
assert.equal(miner.buyUpgrade('resources',wallet),false);
assert.equal(wallet.balance,balance);
console.log('Passed pickup, one-item clicks, merging, swapping, rollback, quick transfers, capacity, upgrade payment and level caps.');

// Multiple workers share one output; rolling back a held stack preserves live production.
const shared = {storage:{},produced:{}};
const first = new Miner(workerTiers[0],shared);
const second = new Miner(workerTiers[1],shared);
const sharedInventory = new Inventory();
const sharedInteraction = new StackInteraction(sharedInventory);
const sharedStore = minerStore(shared);
first.mine(); second.mine();
assert.equal(first.storage,second.storage);
const beforeProduction = Object.values(shared.storage).reduce((sum,n)=>sum+n,0);
const type = Object.keys(shared.storage)[0];
sharedInteraction.click(sharedStore,type,true);
first.mine(); second.mine();
const newlyProduced = Object.values(shared.produced).reduce((sum,n)=>sum+n,0) - beforeProduction;
sharedInteraction.cancel();
assert.equal(Object.values(shared.storage).reduce((sum,n)=>sum+n,0),beforeProduction+newlyProduced);
assert.equal(first.storage,shared.storage);
assert.equal(second.storage,shared.storage);
const previousElapsed = first.elapsed;
first.update(first.cycleSeconds / 2);
assert.ok(first.elapsed > previousElapsed);
console.log('Passed shared output, active production during transfers, safe cancellation, and countdown progression.');
