import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
const cache = new Map();
function moduleURL(file) {
    file = path.resolve(file);
    if (cache.has(file)) return cache.get(file);
    const source = fs.readFileSync(file, 'utf8').replace(/from (['"])(\.\/[^'"]+)\1/g,
        (_, quote, dependency) => `from ${JSON.stringify(moduleURL(path.resolve(path.dirname(file), dependency)))}`);
    const result = 'data:text/javascript;base64,' + Buffer.from(source).toString('base64');
    cache.set(file, result);
    return result;
}

const {default: TutorialFlow} = await import(moduleURL('tutorialFlow.js'));
const {default: World, SPAWN} = await import(moduleURL('world.js'));
const {default: Inventory} = await import(moduleURL('inventory.js'));
const {buyApartment} = await import(moduleURL('apartmentInteraction.js'));
const {buyWorker} = await import(moduleURL('minerShop.js'));
const {workerTiers, gameState} = await import(moduleURL('gameData.js'));
const {sellMaterial} = await import(moduleURL('market.js'));
function fixture() {
    const player = { ...SPAWN, keys: {}, inventory: new Inventory(), miners: [], miningOutput: {storage: {}, produced: {}} };
    player.inventory.add('Radio');
    const world = new World(), gui = {isOpen: false, active: null}, interaction = {held: null};
    player.apartment = world.apartment;
    gameState.balance = 1000;
    return { player, world, gui, interaction, flow: new TutorialFlow(player, world, gui, gameState, interaction) };
}
let f = fixture();
assert.equal(f.flow.frozen, true);
assert.equal(f.flow.canMove, false);
assert.equal(f.flow.canOpenGui('market'), false);
f.flow.choose(false);
assert.equal(f.flow.active, false);
assert.equal(f.flow.frozen, false);
assert.equal(f.flow.canMove, true);
assert.equal(f.flow.canOpenGui('inventory'), true);
assert.equal(f.player.miners.length, 0);
assert.equal(gameState.balance, 1000);
f = fixture();
const {flow, player, world, gui, interaction} = f;
flow.choose(true); assert.equal(flow.state, 'balance');
flow.next(); assert.equal(flow.state, 'spend');
flow.next(); assert.equal(flow.state, 'apartmentWalk');
assert.equal(flow.canMove, true);
assert.equal(flow.canOpenGui('mining-house'), false);
player.x = world.apartment.hitbox.x + world.apartment.hitbox.width / 2;
player.y = world.apartment.hitbox.y - 35;
flow.update(); assert.equal(flow.state, 'apartmentPrompt');
flow.next(); assert.equal(flow.state, 'apartmentBuy');
assert.equal(flow.canMove, false);
assert.equal(buyApartment(world.apartment, {balance: 899}), false);
assert.equal(buyApartment(world.apartment, gameState), true);
assert.equal(gameState.balance, 100);
assert.equal(buyApartment(world.apartment, gameState), false);
flow.update(); assert.equal(flow.state, 'home');
flow.next(); assert.equal(flow.state, 'time');
flow.next(); assert.equal(flow.state, 'minerWalk');
assert.equal(flow.canOpenGui('mining-house'), true);
assert.equal(flow.canOpenGui('market'), false);
gui.isOpen = true; gui.active = 'mining-house';
flow.update(); assert.equal(flow.state, 'minerBuy');
assert.equal(flow.canCloseGui, false);
assert.equal(buyWorker(player, workerTiers.find(t=>t.id==='wooden'), gameState), true);
assert.equal(gameState.balance, 0);
flow.update(); assert.equal(flow.state, 'output');
assert.equal(flow.frozen, true);
flow.next(); assert.equal(flow.state, 'waitOutput');
assert.equal(flow.frozen, false);
flow.update(); assert.equal(flow.state, 'waitOutput');
player.miners[0].update(player.miners[0].cycleSeconds);
flow.update(); assert.equal(flow.state, 'collect');
const material = Object.keys(player.miningOutput.storage)[0];
player.inventory.add(material, 1);
interaction.held = {type: material, count: 1};
flow.update(); assert.equal(flow.state, 'collect', 'Do not advance during an unfinished transfer');
interaction.held = null;
flow.update(); assert.equal(flow.state, 'leaveMine');
assert.equal(flow.material, material);
assert.equal(flow.canCloseGui, true);
gui.isOpen = false; flow.update(); assert.equal(flow.state, 'marketWalk');
assert.equal(flow.canOpenGui('market'), true);
gui.isOpen = true; gui.active = 'market'; flow.update(); assert.equal(flow.state, 'sell');
assert.ok(flow.message.includes(material));
flow.update(); assert.equal(flow.state, 'sell');
assert.equal(sellMaterial(player.inventory,material,1),true);
flow.update(); assert.equal(flow.state, 'leaveMarket');
gui.isOpen = false; flow.update(); assert.equal(flow.state, 'casino');
player.x=50;player.y=50;
flow.next(); assert.equal(flow.state, 'complete');
assert.equal(player.x,SPAWN.x);assert.equal(player.y,SPAWN.y);
flow.next(); assert.equal(flow.active,false);
assert.equal(flow.canMove,true);
console.log('Passed tutorial opt-out, complete guided flow, apartment/worker accounting, transfer completion, real sale, and return to spawn.');
